//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActTransportation
    {
        public long addressID { get; set; }
        public long contractID { get; set; }
        public long transportID { get; set; }
        public string actNumber { get; set; }
        public string CMR { get; set; }
        public Nullable<long> TrailerID { get; set; }
    }
}
