//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid addressID { get; set; }
        public string index { get; set; }
        public string state { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string town { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
        public string type { get; set; }
    }
}
