//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public long contactPersonID { get; set; }
        public long organizationID { get; set; }
        public string FIO { get; set; }
        public Nullable<long> tableNumber { get; set; }
        public string position { get; set; }
    }
}
