//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public long contractID { get; set; }
        public long organizationID { get; set; }
        public string contractNumber { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public string contractType { get; set; }
    
        public virtual ContractStreak ContractStreak { get; set; }
    }
}
