//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingLicence
    {
        public string licenceNumber { get; set; }
        public long organizationID { get; set; }
        public Nullable<bool> A1 { get; set; }
        public string tableNumber { get; set; }
        public Nullable<bool> A { get; set; }
        public Nullable<bool> B { get; set; }
        public Nullable<bool> C { get; set; }
        public Nullable<bool> D { get; set; }
        public Nullable<bool> BE { get; set; }
        public Nullable<bool> CE { get; set; }
        public Nullable<bool> DE { get; set; }
        public Nullable<bool> I { get; set; }
        public Nullable<bool> F { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
    }
}
