//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long addressID { get; set; }
        public long organizationID { get; set; }
        public string tableNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ParentName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string IDnumber { get; set; }
        public string PassportSerie { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportUntil { get; set; }
        public Nullable<System.DateTime> DatePassportFrom { get; set; }
        public string position { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
