//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportStateReport
    {
        public long reportID { get; set; }
        public long organizationID { get; set; }
        public Nullable<long> routeID { get; set; }
        public long transportID { get; set; }
        public long tableNumber { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string location { get; set; }
    }
}
