//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        public long tripID { get; set; }
        public long organizationID { get; set; }
        public string tableNumber { get; set; }
        public Nullable<long> tripNumber { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateUntil { get; set; }
        public Nullable<long> ATS { get; set; }
        public Nullable<decimal> beltoll { get; set; }
        public Nullable<decimal> salaryRate { get; set; }
        public Nullable<decimal> fuelPerOneKm { get; set; }
        public Nullable<decimal> tonnageRate { get; set; }
        public Nullable<decimal> fuelPricePerOneLitre { get; set; }
        public Nullable<decimal> adblue { get; set; }
        public Nullable<decimal> tripExpences { get; set; }
    }
}
