//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCost
    {
        public long typeCostID { get; set; }
        public string typeCostName { get; set; }
        public Nullable<bool> repair { get; set; }
        public Nullable<bool> service { get; set; }
    }
}
