//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybills
    {
        public long waybillID { get; set; }
        public Nullable<int> waybillNumber { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<long> carrierID { get; set; }
        public Nullable<long> carID { get; set; }
        public Nullable<int> trailerID { get; set; }
        public Nullable<int> driversTableNumber { get; set; }
        public Nullable<double> speedometerOnDeparture { get; set; }
        public Nullable<double> speedometerOnReturn { get; set; }
        public Nullable<System.DateTime> departureDateShedule { get; set; }
        public Nullable<System.TimeSpan> departureTimeShedule { get; set; }
        public Nullable<System.DateTime> departureDateFact { get; set; }
        public Nullable<System.TimeSpan> departureTimeFact { get; set; }
        public Nullable<System.DateTime> returnDateShedule { get; set; }
        public Nullable<System.TimeSpan> returnTimeShedule { get; set; }
        public Nullable<System.DateTime> returnDateFact { get; set; }
        public Nullable<System.TimeSpan> returnTimeFact { get; set; }
        public Nullable<double> zeroMileage { get; set; }
        public Nullable<double> engineTime { get; set; }
        public Nullable<double> soecialEquipmentTime { get; set; }
        public Nullable<double> FLMrestOnDeparture { get; set; }
        public Nullable<double> FLMrestOnReturn { get; set; }
    }
}
